### ISSUE TITLE
Weather and prayer timings not working.

### ISSUE THREAD

**Issue by Ysmscorps** [tazzix/AllinOnePebbleFace#1]
Weather and Prayer timings not working. Shows all zeros.

**Comment by tazzix** [comment]
As the Peble servers were shut down, I don't think there is anyway for the watch to communicate with the server side script which was hosted by the company, feel free to send a PR if you know a way to get this to work.

**Comment by Ysmscorps** [comment]
Im sorry, but i dont know whats a PR is? Does it needs a subscription?

**Comment by Ysmscorps** [comment]
Mr Tasnim, if the servers are shut down. I still find other applications were both weather and timings works. Mr. Tasnim can it be reproduced once again to match the new requirements?
